// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Protocol.proto

package se.umu.cs.ads.fildil.messages;

/**
 * Protobuf type {@code Chunk}
 */
public final class Chunk extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Chunk)
    ChunkOrBuilder {
  // Use Chunk.newBuilder() to construct.
  private Chunk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Chunk(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Chunk defaultInstance;
  public static Chunk getDefaultInstance() {
    return defaultInstance;
  }

  public Chunk getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Chunk(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            id_ = input.readInt32();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            buf_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return se.umu.cs.ads.fildil.messages.Protocol.internal_static_Chunk_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return se.umu.cs.ads.fildil.messages.Protocol.internal_static_Chunk_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            se.umu.cs.ads.fildil.messages.Chunk.class, se.umu.cs.ads.fildil.messages.Chunk.Builder.class);
  }

  public static com.google.protobuf.Parser<Chunk> PARSER =
      new com.google.protobuf.AbstractParser<Chunk>() {
    public Chunk parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Chunk(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Chunk> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>required int32 id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int BUF_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString buf_;
  /**
   * <code>required bytes buf = 2;</code>
   *
   * <pre>
   *    required bytes checksum = 3;
   *    required bytes sign = 4;
   * </pre>
   */
  public boolean hasBuf() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required bytes buf = 2;</code>
   *
   * <pre>
   *    required bytes checksum = 3;
   *    required bytes sign = 4;
   * </pre>
   */
  public com.google.protobuf.ByteString getBuf() {
    return buf_;
  }

  private void initFields() {
    id_ = 0;
    buf_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBuf()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, buf_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, buf_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static se.umu.cs.ads.fildil.messages.Chunk parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.umu.cs.ads.fildil.messages.Chunk parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.umu.cs.ads.fildil.messages.Chunk parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.umu.cs.ads.fildil.messages.Chunk parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.umu.cs.ads.fildil.messages.Chunk parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static se.umu.cs.ads.fildil.messages.Chunk parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static se.umu.cs.ads.fildil.messages.Chunk parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static se.umu.cs.ads.fildil.messages.Chunk parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static se.umu.cs.ads.fildil.messages.Chunk parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static se.umu.cs.ads.fildil.messages.Chunk parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(se.umu.cs.ads.fildil.messages.Chunk prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Chunk}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Chunk)
      se.umu.cs.ads.fildil.messages.ChunkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return se.umu.cs.ads.fildil.messages.Protocol.internal_static_Chunk_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return se.umu.cs.ads.fildil.messages.Protocol.internal_static_Chunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              se.umu.cs.ads.fildil.messages.Chunk.class, se.umu.cs.ads.fildil.messages.Chunk.Builder.class);
    }

    // Construct using se.umu.cs.ads.fildil.messages.Chunk.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      id_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      buf_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return se.umu.cs.ads.fildil.messages.Protocol.internal_static_Chunk_descriptor;
    }

    public se.umu.cs.ads.fildil.messages.Chunk getDefaultInstanceForType() {
      return se.umu.cs.ads.fildil.messages.Chunk.getDefaultInstance();
    }

    public se.umu.cs.ads.fildil.messages.Chunk build() {
      se.umu.cs.ads.fildil.messages.Chunk result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public se.umu.cs.ads.fildil.messages.Chunk buildPartial() {
      se.umu.cs.ads.fildil.messages.Chunk result = new se.umu.cs.ads.fildil.messages.Chunk(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.id_ = id_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.buf_ = buf_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof se.umu.cs.ads.fildil.messages.Chunk) {
        return mergeFrom((se.umu.cs.ads.fildil.messages.Chunk)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(se.umu.cs.ads.fildil.messages.Chunk other) {
      if (other == se.umu.cs.ads.fildil.messages.Chunk.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasBuf()) {
        setBuf(other.getBuf());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasId()) {
        
        return false;
      }
      if (!hasBuf()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      se.umu.cs.ads.fildil.messages.Chunk parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (se.umu.cs.ads.fildil.messages.Chunk) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public Builder setId(int value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString buf_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes buf = 2;</code>
     *
     * <pre>
     *    required bytes checksum = 3;
     *    required bytes sign = 4;
     * </pre>
     */
    public boolean hasBuf() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes buf = 2;</code>
     *
     * <pre>
     *    required bytes checksum = 3;
     *    required bytes sign = 4;
     * </pre>
     */
    public com.google.protobuf.ByteString getBuf() {
      return buf_;
    }
    /**
     * <code>required bytes buf = 2;</code>
     *
     * <pre>
     *    required bytes checksum = 3;
     *    required bytes sign = 4;
     * </pre>
     */
    public Builder setBuf(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      buf_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes buf = 2;</code>
     *
     * <pre>
     *    required bytes checksum = 3;
     *    required bytes sign = 4;
     * </pre>
     */
    public Builder clearBuf() {
      bitField0_ = (bitField0_ & ~0x00000002);
      buf_ = getDefaultInstance().getBuf();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Chunk)
  }

  static {
    defaultInstance = new Chunk(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:Chunk)
}

