// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Protocol.proto

package se.umu.cs.ads.fildil.messages;

public interface ChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Chunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>required bytes buf = 2;</code>
   *
   * <pre>
   *    required bytes checksum = 3;
   *    required bytes sign = 4;
   * </pre>
   */
  boolean hasBuf();
  /**
   * <code>required bytes buf = 2;</code>
   *
   * <pre>
   *    required bytes checksum = 3;
   *    required bytes sign = 4;
   * </pre>
   */
  com.google.protobuf.ByteString getBuf();
}
