// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package se.umu.cs.ads.fildil.messages;

public interface ChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Chunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>required string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>required bytes buf = 2;</code>
   */
  boolean hasBuf();
  /**
   * <code>required bytes buf = 2;</code>
   */
  com.google.protobuf.ByteString getBuf();

  /**
   * <code>required bytes mac = 3;</code>
   */
  boolean hasMac();
  /**
   * <code>required bytes mac = 3;</code>
   */
  com.google.protobuf.ByteString getMac();
}
