// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Protocol.proto

package se.umu.cs.ads.fildil.messages;

public interface SendChunkReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendChunkReply)
    com.google.protobuf.MessageOrBuilder {
}
