// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package se.umu.cs.ads.fildil.proto.autogen;

public interface ChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Chunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional bytes buf = 2;</code>
   */
  com.google.protobuf.ByteString getBuf();
}
