// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package se.umu.cs.ads.fildil.proto.autogen;

/**
 * Protobuf type {@code PeerInfo}
 */
public  final class PeerInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PeerInfo)
    PeerInfoOrBuilder {
  // Use PeerInfo.newBuilder() to construct.
  private PeerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PeerInfo() {
    highestChunk_ = 0;
    uuid_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private PeerInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            highestChunk_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            uuid_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              peers_ = com.google.protobuf.MapField.newMapField(
                  PeersDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
            peers__ = input.readMessage(
                PeersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            peers_.getMutableMap().put(
                peers__.getKey(), peers__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return se.umu.cs.ads.fildil.proto.autogen.Protocol.internal_static_PeerInfo_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetPeers();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return se.umu.cs.ads.fildil.proto.autogen.Protocol.internal_static_PeerInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            se.umu.cs.ads.fildil.proto.autogen.PeerInfo.class, se.umu.cs.ads.fildil.proto.autogen.PeerInfo.Builder.class);
  }

  private int bitField0_;
  public static final int HIGHESTCHUNK_FIELD_NUMBER = 1;
  private int highestChunk_;
  /**
   * <code>optional int32 highestChunk = 1;</code>
   */
  public int getHighestChunk() {
    return highestChunk_;
  }

  public static final int UUID_FIELD_NUMBER = 2;
  private volatile java.lang.Object uuid_;
  /**
   * <code>optional string uuid = 2;</code>
   */
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>optional string uuid = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PEERS_FIELD_NUMBER = 3;
  private static final class PeersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Integer>newDefaultInstance(
                se.umu.cs.ads.fildil.proto.autogen.Protocol.internal_static_PeerInfo_PeersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Integer> peers_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
  internalGetPeers() {
    if (peers_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PeersDefaultEntryHolder.defaultEntry);
    }
    return peers_;
  }

  public int getPeersCount() {
    return internalGetPeers().getMap().size();
  }
  /**
   * <pre>
   *address:port
   * </pre>
   *
   * <code>map&lt;string, int32&gt; peers = 3;</code>
   */

  public boolean containsPeers(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetPeers().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPeersMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Integer> getPeers() {
    return getPeersMap();
  }
  /**
   * <pre>
   *address:port
   * </pre>
   *
   * <code>map&lt;string, int32&gt; peers = 3;</code>
   */

  public java.util.Map<java.lang.String, java.lang.Integer> getPeersMap() {
    return internalGetPeers().getMap();
  }
  /**
   * <pre>
   *address:port
   * </pre>
   *
   * <code>map&lt;string, int32&gt; peers = 3;</code>
   */

  public int getPeersOrDefault(
      java.lang.String key,
      int defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetPeers().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *address:port
   * </pre>
   *
   * <code>map&lt;string, int32&gt; peers = 3;</code>
   */

  public int getPeersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.Integer> map =
        internalGetPeers().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (highestChunk_ != 0) {
      output.writeInt32(1, highestChunk_);
    }
    if (!getUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uuid_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetPeers(),
        PeersDefaultEntryHolder.defaultEntry,
        3);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (highestChunk_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, highestChunk_);
    }
    if (!getUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uuid_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
         : internalGetPeers().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
      peers__ = PeersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, peers__);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof se.umu.cs.ads.fildil.proto.autogen.PeerInfo)) {
      return super.equals(obj);
    }
    se.umu.cs.ads.fildil.proto.autogen.PeerInfo other = (se.umu.cs.ads.fildil.proto.autogen.PeerInfo) obj;

    boolean result = true;
    result = result && (getHighestChunk()
        == other.getHighestChunk());
    result = result && getUuid()
        .equals(other.getUuid());
    result = result && internalGetPeers().equals(
        other.internalGetPeers());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + HIGHESTCHUNK_FIELD_NUMBER;
    hash = (53 * hash) + getHighestChunk();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    if (!internalGetPeers().getMap().isEmpty()) {
      hash = (37 * hash) + PEERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPeers().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(se.umu.cs.ads.fildil.proto.autogen.PeerInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PeerInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PeerInfo)
      se.umu.cs.ads.fildil.proto.autogen.PeerInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return se.umu.cs.ads.fildil.proto.autogen.Protocol.internal_static_PeerInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetPeers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutablePeers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return se.umu.cs.ads.fildil.proto.autogen.Protocol.internal_static_PeerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              se.umu.cs.ads.fildil.proto.autogen.PeerInfo.class, se.umu.cs.ads.fildil.proto.autogen.PeerInfo.Builder.class);
    }

    // Construct using se.umu.cs.ads.fildil.proto.autogen.PeerInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      highestChunk_ = 0;

      uuid_ = "";

      internalGetMutablePeers().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return se.umu.cs.ads.fildil.proto.autogen.Protocol.internal_static_PeerInfo_descriptor;
    }

    public se.umu.cs.ads.fildil.proto.autogen.PeerInfo getDefaultInstanceForType() {
      return se.umu.cs.ads.fildil.proto.autogen.PeerInfo.getDefaultInstance();
    }

    public se.umu.cs.ads.fildil.proto.autogen.PeerInfo build() {
      se.umu.cs.ads.fildil.proto.autogen.PeerInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public se.umu.cs.ads.fildil.proto.autogen.PeerInfo buildPartial() {
      se.umu.cs.ads.fildil.proto.autogen.PeerInfo result = new se.umu.cs.ads.fildil.proto.autogen.PeerInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.highestChunk_ = highestChunk_;
      result.uuid_ = uuid_;
      result.peers_ = internalGetPeers();
      result.peers_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof se.umu.cs.ads.fildil.proto.autogen.PeerInfo) {
        return mergeFrom((se.umu.cs.ads.fildil.proto.autogen.PeerInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(se.umu.cs.ads.fildil.proto.autogen.PeerInfo other) {
      if (other == se.umu.cs.ads.fildil.proto.autogen.PeerInfo.getDefaultInstance()) return this;
      if (other.getHighestChunk() != 0) {
        setHighestChunk(other.getHighestChunk());
      }
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      internalGetMutablePeers().mergeFrom(
          other.internalGetPeers());
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      se.umu.cs.ads.fildil.proto.autogen.PeerInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (se.umu.cs.ads.fildil.proto.autogen.PeerInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int highestChunk_ ;
    /**
     * <code>optional int32 highestChunk = 1;</code>
     */
    public int getHighestChunk() {
      return highestChunk_;
    }
    /**
     * <code>optional int32 highestChunk = 1;</code>
     */
    public Builder setHighestChunk(int value) {
      
      highestChunk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 highestChunk = 1;</code>
     */
    public Builder clearHighestChunk() {
      
      highestChunk_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>optional string uuid = 2;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string uuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string uuid = 2;</code>
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string uuid = 2;</code>
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string uuid = 2;</code>
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> peers_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetPeers() {
      if (peers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PeersDefaultEntryHolder.defaultEntry);
      }
      return peers_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetMutablePeers() {
      onChanged();;
      if (peers_ == null) {
        peers_ = com.google.protobuf.MapField.newMapField(
            PeersDefaultEntryHolder.defaultEntry);
      }
      if (!peers_.isMutable()) {
        peers_ = peers_.copy();
      }
      return peers_;
    }

    public int getPeersCount() {
      return internalGetPeers().getMap().size();
    }
    /**
     * <pre>
     *address:port
     * </pre>
     *
     * <code>map&lt;string, int32&gt; peers = 3;</code>
     */

    public boolean containsPeers(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPeers().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPeersMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getPeers() {
      return getPeersMap();
    }
    /**
     * <pre>
     *address:port
     * </pre>
     *
     * <code>map&lt;string, int32&gt; peers = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getPeersMap() {
      return internalGetPeers().getMap();
    }
    /**
     * <pre>
     *address:port
     * </pre>
     *
     * <code>map&lt;string, int32&gt; peers = 3;</code>
     */

    public int getPeersOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetPeers().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *address:port
     * </pre>
     *
     * <code>map&lt;string, int32&gt; peers = 3;</code>
     */

    public int getPeersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetPeers().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearPeers() {
      getMutablePeers().clear();
      return this;
    }
    /**
     * <pre>
     *address:port
     * </pre>
     *
     * <code>map&lt;string, int32&gt; peers = 3;</code>
     */

    public Builder removePeers(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      getMutablePeers().remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
    getMutablePeers() {
      return internalGetMutablePeers().getMutableMap();
    }
    /**
     * <pre>
     *address:port
     * </pre>
     *
     * <code>map&lt;string, int32&gt; peers = 3;</code>
     */
    public Builder putPeers(
        java.lang.String key,
        int value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      
      getMutablePeers().put(key, value);
      return this;
    }
    /**
     * <pre>
     *address:port
     * </pre>
     *
     * <code>map&lt;string, int32&gt; peers = 3;</code>
     */

    public Builder putAllPeers(
        java.util.Map<java.lang.String, java.lang.Integer> values) {
      getMutablePeers().putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:PeerInfo)
  }

  // @@protoc_insertion_point(class_scope:PeerInfo)
  private static final se.umu.cs.ads.fildil.proto.autogen.PeerInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new se.umu.cs.ads.fildil.proto.autogen.PeerInfo();
  }

  public static se.umu.cs.ads.fildil.proto.autogen.PeerInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PeerInfo>
      PARSER = new com.google.protobuf.AbstractParser<PeerInfo>() {
    public PeerInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new PeerInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PeerInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PeerInfo> getParserForType() {
    return PARSER;
  }

  public se.umu.cs.ads.fildil.proto.autogen.PeerInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

