// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package se.umu.cs.ads.fildil.proto.autogen;

public interface ReceiveChunkReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReceiveChunkReply)
    com.google.protobuf.MessageOrBuilder {
}
