// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

package se.umu.cs.ads.fildil.proto.autogen;

public interface SendChunkReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendChunkReply)
    com.google.protobuf.MessageOrBuilder {
}
